baseURL = "http://money.geekylife.net"
title = "Getting Rich with a Geeky Way"
theme = "hugo-nuo"
enableRobotsTXT = true
pygmentsuseclasses = true
PygmentsCodeFences = true
canonifyurls = true
publishDir = "docs"

# Disqus Username
disqusShortname = "money-geeky-life"

# Google Analytics UA number
googleAnalytics = "UA-106504664-1"

# Copyright of your post
copyright = "© Money Geeky Life 2017."

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Works"
  weight = 20
  identifier = "works"
  url = "https://github.com/laozhu"

# Add your own params here
[params]
  author = "Money Geeker"
  avatar = "/img/avatar.jpg"
  seotitle = "Money Geeky Life"
  subtitle = "~ Save, Invest, Contribute ~"
  description = "This is melaozhu's personal blog, he takes note here while exploring the new world."
  paginate = 10

  # Choose your social networks
  email = "moneygeekylife@gmail.com"
  # github = "laozhu"
  # twitter = "melaozhu"
  # linkedin = "melaozhu"
  # wechat= "/img/qrcode.jpg"  # Replace with your wechat qrcode image
  # facebook = "melaozhu"
  # google = "109063353665074282689"
  # instagram = "melaozhu"
  # youtube = "melaozhu"
  # vimeo = "melaozhu"
  # medium = "melaozhu"
  # quora = "melaozhu"
  # pinterest = "laozhu"
  # dribbble = "laozhu"
  # behance = "melaozhu"
  # jsfiddle = "laozhu"
  # codepen = "laozhu"
  # zhihu = "melaozhu"
  # douban = "melaozhu"
  # bilibili = "13395348"

  # Changyan Comments (China Only)
  # changyan = true
  # changyanId = "cyt3toRiB"
  # changyanConf = "prod_0908b1cb9a581501753cce1ed074dbe3"

  # Google Webmaster
  # https://www.google.com/webmasters/
  googleSiteVerification = "_moDmnnBNVLBN1rzNxyGUGdPHE20YgbmrtzLIbxaWFc"

  # Bing Webmaster
  # https://www.bing.com/toolbox/webmaster/
  # msValidate = "22596E34341DD1D17D6022C44647E587"

  # Sogou Webmaster (China Only)
  # http://zhanzhang.sogou.com/
  #sogouSiteVerification = "m2jktMQTZm"
